### ISSUE TITLE
Document report: [Technical 1.0]

### ISSUE THREAD

**Issue by Clementine951** [algosup/2023-2024-project-5-flutter-team-3#12]
### Description

- Why is this text red?
<img width="775" alt="Screenshot 2024-06-03 at 19 25 36" src="https://github.com/algosup/2023-2024-project-5-flutter-team-3/assets/78617457/c95ad15a-0e80-4d79-9379-68c08b669eed">

- What the developer is going to use for the location of the candidate?
- Isn't an arrow missing on the company side between "Open chat in the app" and "Read chat messages"?

<img width="687" alt="Screenshot 2024-06-03 at 19 33 09" src="https://github.com/algosup/2023-2024-project-5-flutter-team-3/assets/78617457/9fcbe92d-d592-4d67-a7fb-2a4f46cec480">

- There is no explanation about what to do about the data privacy 
  - Take into account that terms and conditions are not the same than data privacy policies.

### Severity

2. Medium (Should be fixed soon)

### Version

Version 1.0

### Expected Correction

Correction of the previous points.
Data privacy is a legal part of an application, you really should talk about it somewhere.

### Other Details

Still missing the minimum and the maximum length pour the text fields. 
Which is also needed for the test cases.

**Comment by MaximeAlgosup** [comment]
Corrected with commit 7cde9cca3e1bb6fa13fc8b26d011c5ce4c5edf0a

**Comment by Clementine951** [comment]
The missing changes of this issue have been moved to issue #17, for more clarity.
