### ISSUE TITLE
Bug report: [Build 1 | Register + Extra]

### ISSUE THREAD

**Issue by Clementine951** [algosup/2023-2024-project-5-flutter-team-3#14]
### Issue description

These tests have been realised on both:

- External - iPhone 13 - 15.6.1
- iOS simulator - iPhone 15 - 17.4
- Android studio - Pixel a3

---

**Test cases ID: COM_REG102, CAN_REG108, CC_EXT113, CC_EXT116**

- Hard coded at the moment

**Test cases ID: COM_REG103, COM_REG105, COM_REG106, CAN_REG109, CAN_REG111, CAN_REG112, CC_EXT117**

- No buttons

**Test cases ID: CC_EXT114, CC_EXT115, CC_EXT118, COM_EXT119, COM_EXT120, CAN_EXT121, CAN_EXT122**
|ID|UX|Bug|Problem|
| - | - | - | - |
|CC_EXT114| |x|No maximum, neither minimum length|
|CC_EXT115|x|x|When on login, an overflow appears|
|CC_EXT118|x|x| Some parts of the page are in a staggered arrangement|
|COM_EXT119 + CAN_EXT121|x|x|No different side at the moment. Got different number of pixels for each device. See in steps taken. When rotating the phone, the app is not responsive any more.|
|COM_EXT120 + CAN_EXT122|x|| It can be annoying to have the pages switch in this manner. See the video in steps taken|

### Issue priority

2. Medium (Should be fixed soon)

### Version

Development

### Steps taken

**CC_EXT115:**
- Go to the Login page
- Click on the email field

![IMG_5757](https://github.com/algosup/2023-2024-project-5-flutter-team-3/assets/78617457/289f4c1a-1e53-44a0-bba2-eaf4585593e8)

- Click on the password field

![IMG_5758](https://github.com/algosup/2023-2024-project-5-flutter-team-3/assets/78617457/3341f5d5-52be-4c91-bb9b-547920765cf5)

- This happens when the keyboard is displayed
- Same on android

![Screenshot_1717492834](https://github.com/algosup/2023-2024-project-5-flutter-team-3/assets/78617457/5144e865-6514-4817-b03f-52fd1f0abfbe)
![Screenshot_1717492831](https://github.com/algosup/2023-2024-project-5-flutter-team-3/assets/78617457/f7bf7861-3109-4363-bfc0-567f3f12d86a)

**CC_EXT118:**

![Screenshot_1717492840](https://github.com/algosup/2023-2024-project-5-flutter-team-3/assets/78617457/89035590-5c05-42da-910b-38a9efc61f3b)
![Simulator Screenshot - iPhone 15 Pro - 2024-06-04 at 09 58 16](https://github.com/algosup/2023-2024-project-5-flutter-team-3/assets/78617457/d032436e-290d-4872-8c5b-d373b26f6f1c)
![IMG_5763](https://github.com/algosup/2023-2024-project-5-flutter-team-3/assets/78617457/5a197f53-3f1c-4b0a-a443-a32643cb0ff1)

**COM_EXT119 + CAN_EXT121:**
- iPhone : 53 px
![IMG_5759](https://github.com/algosup/2023-2024-project-5-flutter-team-3/assets/78617457/1d6b3fab-afde-47ac-b04f-f4143c0da378)
- iOS simulator : 45 px 
![Simulator Screenshot - iPhone 15 Pro - 2024-06-04 at 11 27 59](https://github.com/algosup/2023-2024-project-5-flutter-team-3/assets/78617457/eb054693-d87d-4956-b3b1-71a9c9612c3b)
- Android : 181 px
![Screenshot_1717492840](https://github.com/algosup/2023-2024-project-5-flutter-team-3/assets/78617457/e1c796ca-3275-4bc4-8f40-78cc8981f28d)

- Phone rotated

![Simulator Screenshot - iPhone 15 Pro - 2024-06-04 at 13 43 09](https://github.com/algosup/2023-2024-project-5-flutter-team-3/assets/78617457/d8a568ab-0e43-4f8f-998b-cedaefe6acf1)

**COM_EXT120 + CAN_EXT122**

https://github.com/algosup/2023-2024-project-5-flutter-team-3/assets/78617457/eb6d148f-808b-43d8-b064-f28bca907463

### Expected result

Would have expected to see at least the buttons without design.
The hard coded part have been put apart for the moment.

The app should be restricted to a profile view, to avoid the unresponsiveness of the horizontal view.

### This issue was tested on a development release

52f31ed

**Comment by Biohazardyee** [comment]
Good morning @Clementine951. 

Let me inform you that all these issues have been fixed during Pull Request #33. 

We have decided to keep the page navigation this way for design reasons. 
We have fixed the cards overflow by making them scrollable! 
And the overflow on the login page have been fixed as well after further review. 

Thank you for your feedback.

**Comment by Clementine951** [comment]
I decided to close this issue because of the opening of a new one. #37
