### ISSUE TITLE
Document report: [Technical | Text field]

### ISSUE THREAD

**Issue by Clementine951** [algosup/2023-2024-project-5-flutter-team-3#20]
### Description

On 'Text Field' part, you are exposing the fact that fields should have minimum and maximum length. 

Can a user put a description of 0 characters or 2 000 characters? 

### Severity

4. Critical (Severe impact)

### Version

1.01

### Expected Correction

You should find the right limit for the: 
- passwords
- description of a candidate
- description of a company
- ...

### Other Details

These limits will also be useful for the development of the responsiveness of the app, as thanks to this the developer will know in advance the possible mobility of the fields.

**Comment by Clementine951** [comment]
My bad

**Comment by MaximeAlgosup** [comment]
Results in commit: d5a750ee186ac41e782bf86855da0d594d99428b
