### ISSUE TITLE
Document report: [ User Manual | Overview ]

### ISSUE THREAD

**Issue by Clementine951** [algosup/2023-2024-project-5-flutter-team-3#22]
### Description

As a user manual a document for the users, think about making it “prettier”. 

- For the moment, the document looks kind of empty / not well proportionate
  - The pictures are not centred, the titles are not visible enough
- The pictures related to a text should be on the same page
  - Pages 12-13, the login picture is on a different page than the explanations.

### Severity

1. Low (Slightly annoying)

### Version

430dc9b

### Expected Correction

Use something like Google Docs or Pages (on macOS) to organise your document better.

### Other Details

You should put the logo of the application on the first page or on each footer of the pages.

**Comment by AlexisLasselin** [comment]
![Notes taking](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExY3JwbDI4dW9vMm85eDZldDA1M3kwYmVsaW1kejJ3NmI3Y3U4dHo0aiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/xTiTnwmI2nlBpITMre/giphy.gif)

I'll take your comments into account and it will be done for the final version only, I prefer to write in Markdown on VSCode.

**Comment by AlexisLasselin** [comment]
Gdocs updated, the pdf commit will be commented once published. 👌🏻

**Comment by AlexisLasselin** [comment]
05a1390543d00cef6af39899a9adc1a3bad7856b

**Comment by Clementine951** [comment]
This issue has been resolved with your push.
