### ISSUE TITLE
Document report: [User Manual | Overview 2]

### ISSUE THREAD

**Issue by Clementine951** [algosup/2023-2024-project-5-flutter-team-3#26]
### Description

1. The logo isn't visible anywhere.

2. Where will this document be findable by the users?
   - App Store?
   - On the app?
   - Pdf?

3. On GitHub, your documents are not in a folder on the user-manual branch. 
   - Two .md
   - Two .pdf
   - UMImages folder
   
4. What are all the functionalities of the app? 

5. The titles are not visible enough, when looking for a specific part, you can easily struggle to find it. 

6. You are missing consistency between all the list on your document.

### Severity

2. Medium (Should be fixed soon)

### Version

430dc9b

### Expected Correction

1. Think about adding the application logo on the footer or the header.

2. If in pdf, think about adding a front page, to know what the document is talking about without having to read it.

3. Move the files into the documents folder used for all the documents.

5. Add some design to your document.

6. Choose a syntax for your lists, and hold on this one.

**Comment by AlexisLasselin** [comment]
05a1390543d00cef6af39899a9adc1a3bad7856b

**Comment by AlexisLasselin** [comment]
And the folder `UMImages`will be deleted for the final commit, I just need a place to save pictures while creating the file

**Comment by Clementine951** [comment]
Most of the problems of this issue have been resolved. 
The only missing point is the consistency of the lists. 
You need consistency between all the lists.
-> Page 6 and 8 
  - Page 6, your list is containing ";" at each line and ends with "."
  - Page 8, your list isn't containing anything but the last with a "."

The issue number 2 is still in pending.

**Comment by AlexisLasselin** [comment]
should be done here:
865d9c4112d42c525b44ae1b3d7911a9300ebfde

**Comment by Clementine951** [comment]
👍
