### ISSUE TITLE
Document report: [User Manual | Table of contents]

### ISSUE THREAD

**Issue by Clementine951** [algosup/2023-2024-project-5-flutter-team-3#27]
### Description

On your table of content, you should add the number of the pages. 

These two lines on this part are not useful.

<img width="254" alt="Screenshot 2024-06-10 at 11 37 48" src="https://github.com/algosup/2023-2024-project-5-flutter-team-3/assets/78617457/ff8ea095-8337-44d1-9c82-d0a9c6824d8e">

### Severity

1. Low (Slightly annoying)

### Version

430dc9b

### Expected Correction

Having a table of contents that looks like this should be better.

![image](https://github.com/algosup/2023-2024-project-5-flutter-team-3/assets/78617457/1487de6e-282d-404f-a8fa-03561e778c85)

### Other Details

The issues have been done in small format with the demand of the writer.

**Comment by AlexisLasselin** [comment]
Done in the gdocs, pdf commit will be commented once published

**Comment by AlexisLasselin** [comment]
05a1390543d00cef6af39899a9adc1a3bad7856b

**Comment by Clementine951** [comment]
Nice
