### ISSUE TITLE
Document report: [User Manual | Introduction + Installing]

### ISSUE THREAD

**Issue by Clementine951** [algosup/2023-2024-project-5-flutter-team-3#28]
### Description

1. Check your eligibility
- This part could be in only two page 
    - Android 
    - iOS
- Are you sure that the way to get the version of the OS is the same on all Android devices?

2. Installing
- Maybe a preview of what the page on Play Store or iOS will look like could be nice

### Severity

4. Critical (Severe impact)

### Version

430dc9b

### Expected Correction

1. You should put the tutorial for checking the OS version for iOS on one page and Android on another page. 
At the moment, you have 7 pages for only this part.

**Comment by AlexisLasselin** [comment]
Everything is on one page for each version, however, Android are build the same way no matter which brand you're using, and regarding the Play Store / iOS, maybe we should ask @habicll to produce to do it.

**Comment by AlexisLasselin** [comment]
05a1390543d00cef6af39899a9adc1a3bad7856b

**Comment by Clementine951** [comment]
The pages are well separated. 
Good point, the program manager should have created this page. @LucasAub
