### ISSUE TITLE
Document report: [User Manual | First Steps]

### ISSUE THREAD

**Issue by Clementine951** [algosup/2023-2024-project-5-flutter-team-3#29]
### Description

1. The screen used for the tutorial should be on the same page as the writing.
- If the user can’t see directly the screenshot related to the writing, the image will be seen only after finishing the tutorial. Or worst case scenario, when the user will start to struggle with the tutorial.

2. Think about mixing the writing and the images

3. There is a non-consistency within the lists.  
- You mixed with " " and ";" and ","

<img width="185" alt="Screenshot 2024-06-10 at 11 56 57" src="https://github.com/algosup/2023-2024-project-5-flutter-team-3/assets/78617457/2c1618e5-502f-47c4-aa23-9d6ec6c12d6f">

### Severity

3. High (Immediate attention needed)

### Version

430dc9b

### Expected Correction

2. You could use the image of the application as legend 
- You can use arrow to show directly the user which field are what

3. You should choose a specific syntax for your lists and follow it every time

**Comment by AlexisLasselin** [comment]
Should be done, I'll ask you to re check before the final push

**Comment by AlexisLasselin** [comment]
05a1390543d00cef6af39899a9adc1a3bad7856b

**Comment by Clementine951** [comment]
👌
