### ISSUE TITLE
Document report: [User Manual | Login - Create - Matching]

### ISSUE THREAD

**Issue by Clementine951** [algosup/2023-2024-project-5-flutter-team-3#30]
### Description

1. Login 
- Same as said previously, the images are not on the same page as the description

2. Create
- This part is missing

3. Matching
- Is there a possibility for to see the information on another page? 
- Is this page scrollable?
- You should resize the pictures
- Are the buttons usable?

### Severity

3. High (Immediate attention needed)

### Version

430dc9b

### Expected Correction

1. You can use arrow to show directly to the users which part are used for what.
2. To do 
3. What happens when too much information?
3. Show that the buttons are also working

**Comment by AlexisLasselin** [comment]
only the create part missing there

05a1390543d00cef6af39899a9adc1a3bad7856b

**Comment by Clementine951** [comment]
This issue been mostly resolved, I decided to close it and put the remaining issues on the issue #34.
